apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: "todo123"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "hussein.test.2033@gmail.com"
  SMTP_PASS: "xxxxxxxxxxxxx"